### ISSUE TITLE
Compatibility with fastapi (^0.54.1)

### ISSUE THREAD

**Issue by tbikeev** [digitalliving/openapi-to-fastapi#7]
Hello, many thanks for your very useful library,

I am trying to add it as dependency to https://github.com/tiangolo/full-stack-fastapi-postgresql but getting compatibility failure.
```
#9 4.739   Because openapi-to-fastapi (0.1.4) depends on fastapi (>=0.47.1,<0.48.0)
#9 4.739    and app depends on fastapi (^0.54.1), openapi-to-fastapi is forbidden.
#9 4.739   So, because app depends on openapi-to-fastapi (0.1.4), version solving failed.
```
Any specific reason to pinning it on the fixed 0.47.1 version of FastAPI? 
Cheers, Thomas

**Comment by joakimnordling** [comment]
Hi @tbikeev,

Thanks for raising this issue!

It's just due to normal best practice of pinning it according to semantic versioning, based on the version we originally used it with. Unfortunately FastAPI has got rather many releases that at least according to the semantic versioning contain breaking changes.

A quick check from my side revealed that the unit tests pass all the way up to version 0.57.0 of FastAPI. Apparently 0.58.0 included some change that at least causes the unit tests to fail and I didn't now have time to check it in more detail than that. So in essence solving that for your particular case should be possible if we'd just update the dependency to be `>=0.47.1, < 0.58`, but I think we'd really want to try to fix it to work with newer versions of FastAPI as well. 

I'll ping @fbjorn to ask him if he'd want to have a look at what's causing the issue with 0.58 and newer and also check if he thinks we'd want to do a small intermediate release where we'd just expand the allowed versions to be `>=0.47.1, < 0.58`, as that would solve this particular request. I was a bit opportunistic and made a PR that would implement that intermediate fix.

**Comment by tbikeev** [comment]
@joakimnordling , @fbjorn - Thanks for the explanations!
